"""
evaluate.py  (v2 — Balanced Evaluation + Confusion Matrix)
==========================================================
Step 3 of the Gold Standard pipeline.

Loads the balanced pan25_test.csv (generated by pan25_extractor.py v2),
runs the fine-tuned BERT model, and produces a full confusion matrix
with mathematically valid metrics.

Output: Prints TP, FP, TN, FN, Precision, Recall, F1, Accuracy.

Usage : python evaluate.py [--batch B]
"""

import os
import argparse
import pandas as pd
import numpy as np

import torch
from torch.utils.data import Dataset, DataLoader
from torch.amp import autocast
from transformers import BertTokenizer, BertForSequenceClassification
from sklearn.metrics import (
    precision_recall_fscore_support,
    accuracy_score,
    confusion_matrix,
    classification_report,
)
from tqdm import tqdm

# ── Settings ──────────────────────────────────────────────────────────────────
BERT_MODEL_DIR = "bert_model"
TEST_CSV       = "pan25_test.csv"
MAX_LENGTH     = 256


# ── Dataset class (lazy tokenization) ─────────────────────────────────────────

class PlagiarismDataset(Dataset):
    def __init__(self, texts_a, texts_b, labels, tokenizer, max_len):
        self.texts_a   = list(texts_a)
        self.texts_b   = list(texts_b)
        self.labels    = list(labels)
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts_a[idx],
            self.texts_b[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt",
        )
        item = {
            "input_ids":      enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "labels":         torch.tensor(self.labels[idx], dtype=torch.long),
        }
        if "token_type_ids" in enc:
            item["token_type_ids"] = enc["token_type_ids"].squeeze(0)
        return item


# ── Main ──────────────────────────────────────────────────────────────────────

def main(batch_size: int):
    # ── Device setup ──────────────────────────────────────────────────────
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    use_amp = device.type == "cuda"

    print(f"{'='*60}")
    print(f"BERT Evaluation — Confusion Matrix")
    print(f"{'='*60}")
    print(f"Device     : {device}")
    if device.type == "cuda":
        print(f"GPU        : {torch.cuda.get_device_name(0)}")

    # ── Load model ────────────────────────────────────────────────────────
    if not os.path.isdir(BERT_MODEL_DIR):
        print(f"ERROR: '{BERT_MODEL_DIR}/' not found. Run train_bert.py first.")
        return

    print(f"Loading model from {BERT_MODEL_DIR}/ ...")
    tokenizer = BertTokenizer.from_pretrained(BERT_MODEL_DIR)
    model     = BertForSequenceClassification.from_pretrained(BERT_MODEL_DIR)
    model.to(device)
    model.eval()

    # ── Load test data ────────────────────────────────────────────────────
    if not os.path.exists(TEST_CSV):
        print(f"ERROR: '{TEST_CSV}' not found. Run pan25_extractor.py first.")
        return

    print(f"Loading {TEST_CSV} ...")
    test_df = pd.read_csv(TEST_CSV).dropna()
    n_pos   = (test_df["label"] == 1).sum()
    n_neg   = (test_df["label"] == 0).sum()
    print(f"  Total: {len(test_df)} | Pos: {n_pos} | Neg: {n_neg}")

    if n_neg == 0:
        print("\n⚠️  WARNING: Test set has ZERO negative samples!")
        print("   Precision/Recall will be meaningless.")
        print("   Re-run pan25_extractor.py v2 to generate balanced splits.")

    # ── Prepare dataloader ────────────────────────────────────────────────
    print("Tokenizing test set ...")
    test_ds = PlagiarismDataset(
        test_df["suspicious_text"], test_df["source_text"],
        test_df["label"], tokenizer, MAX_LENGTH
    )
    pin = device.type == "cuda"
    test_loader = DataLoader(
        test_ds, batch_size=batch_size, shuffle=False,
        num_workers=2, pin_memory=pin
    )

    # ── Run inference ─────────────────────────────────────────────────────
    all_preds  = []
    all_labels = []
    all_probs  = []

    with torch.no_grad():
        for batch in tqdm(test_loader, desc="Evaluating"):
            ids   = batch["input_ids"].to(device)
            mask  = batch["attention_mask"].to(device)
            types = batch.get("token_type_ids")
            if types is not None:
                types = types.to(device)
            lbls  = batch["labels"]

            kwargs = {"input_ids": ids, "attention_mask": mask}
            if types is not None:
                kwargs["token_type_ids"] = types

            with autocast("cuda", enabled=use_amp):
                out = model(**kwargs)

            probs = torch.softmax(out.logits, dim=1)[:, 1]
            preds = (probs >= 0.60).long()  # same threshold as runtime

            all_probs.extend(probs.cpu().numpy())
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(lbls.numpy())

    all_preds  = np.array(all_preds)
    all_labels = np.array(all_labels)
    all_probs  = np.array(all_probs)

    # ── Confusion Matrix ──────────────────────────────────────────────────
    cm = confusion_matrix(all_labels, all_preds, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    p, r, f1, _ = precision_recall_fscore_support(
        all_labels, all_preds, average="binary", zero_division=0
    )
    acc = accuracy_score(all_labels, all_preds)

    print(f"\n{'='*60}")
    print(f"CONFUSION MATRIX")
    print(f"{'='*60}")
    print(f"                  Predicted Neg    Predicted Pos")
    print(f"  Actual Neg         TN={tn:<6}       FP={fp}")
    print(f"  Actual Pos         FN={fn:<6}       TP={tp}")
    print(f"{'='*60}")
    print(f"  True  Positives (TP) : {tp}")
    print(f"  False Positives (FP) : {fp}")
    print(f"  True  Negatives (TN) : {tn}")
    print(f"  False Negatives (FN) : {fn}")
    print(f"{'─'*60}")
    print(f"  Precision   : {p:.4f}    (TP / (TP + FP))")
    print(f"  Recall      : {r:.4f}    (TP / (TP + FN))")
    print(f"  F1-Score    : {f1:.4f}   (2 × P × R / (P + R))")
    print(f"  Accuracy    : {acc:.4f}   ((TP + TN) / Total)")
    print(f"{'='*60}")

    # ── Full classification report ────────────────────────────────────────
    print("\nDetailed Classification Report:")
    print(classification_report(
        all_labels, all_preds,
        target_names=["Original (0)", "Plagiarized (1)"],
        digits=4
    ))

    # ── Save results to CSV ───────────────────────────────────────────────
    results_path = "evaluation_results.csv"
    pd.DataFrame({
        "metric":    ["TP", "FP", "TN", "FN", "Precision", "Recall", "F1", "Accuracy"],
        "value":     [tp,   fp,   tn,   fn,   round(p,4), round(r,4), round(f1,4), round(acc,4)],
    }).to_csv(results_path, index=False)
    print(f"\nResults saved to {results_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--batch", type=int, default=32,
                        help="Batch size for evaluation (default 32)")
    args = parser.parse_args()
    main(args.batch)
