"""
train_bert.py  (v2 — Colab/GPU-Ready, No Data Leakage)
======================================================
Step 2 of the Gold Standard pipeline.

Loads pre-split CSVs (pan25_train.csv, pan25_val.csv) generated by
pan25_extractor.py v2. No row-level splitting here — the document-level
split already happened upstream, eliminating data leakage.

GPU/CUDA: Fully supports T4, V100, A100 via torch.cuda.amp mixed
precision. Falls back to CPU gracefully.

Input : pan25_train.csv, pan25_val.csv
Output: bert_model/

Usage : python train_bert.py [--epochs E] [--batch B]
"""

import os
import argparse
import pandas as pd
import numpy as np
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

import torch
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.amp import GradScaler, autocast
from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    get_linear_schedule_with_warmup,
)
from tqdm import tqdm

# ── Settings ──────────────────────────────────────────────────────────────────
MODEL_NAME = "bert-base-uncased"
OUTPUT_DIR = "bert_model"
TRAIN_CSV  = "pan25_train.csv"
VAL_CSV    = "pan25_val.csv"
MAX_LENGTH = 256
SEED       = 42


# ── Dataset class (lazy tokenization — handles 600K+ rows) ───────────────────

class PlagiarismDataset(Dataset):
    """Tokenizes each sample on-the-fly in __getitem__ to avoid
    loading 600K tokenized sequences into RAM at once."""

    def __init__(self, texts_a, texts_b, labels, tokenizer, max_len):
        self.texts_a   = list(texts_a)
        self.texts_b   = list(texts_b)
        self.labels    = list(labels)
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts_a[idx],
            self.texts_b[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt",
        )
        item = {
            "input_ids":      enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "labels":         torch.tensor(self.labels[idx], dtype=torch.long),
        }
        if "token_type_ids" in enc:
            item["token_type_ids"] = enc["token_type_ids"].squeeze(0)
        return item


# ── Evaluation helper ─────────────────────────────────────────────────────────

@torch.no_grad()
def evaluate_model(model, loader, device):
    model.eval()
    all_preds, all_labels = [], []

    for batch in tqdm(loader, desc="  Evaluating", leave=False):
        ids   = batch["input_ids"].to(device)
        mask  = batch["attention_mask"].to(device)
        types = batch.get("token_type_ids")
        if types is not None:
            types = types.to(device)
        lbls  = batch["labels"].to(device)

        kwargs = {"input_ids": ids, "attention_mask": mask}
        if types is not None:
            kwargs["token_type_ids"] = types

        out   = model(**kwargs)
        preds = torch.argmax(out.logits, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(lbls.cpu().numpy())

    p, r, f1, _ = precision_recall_fscore_support(
        all_labels, all_preds, average="binary", zero_division=0
    )
    acc = accuracy_score(all_labels, all_preds)
    return {"precision": p, "recall": r, "f1": f1, "accuracy": acc}


# ── Main ──────────────────────────────────────────────────────────────────────

def main(n_epochs: int, batch_size: int):
    torch.manual_seed(SEED)
    np.random.seed(SEED)

    # ── Device setup ──────────────────────────────────────────────────────
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    use_amp = device.type == "cuda"
    scaler = GradScaler("cuda", enabled=use_amp)

    print(f"{'='*60}")
    print(f"Device     : {device}")
    if device.type == "cuda":
        print(f"GPU        : {torch.cuda.get_device_name(0)}")
        print(f"GPU Memory : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
        print(f"AMP        : Enabled (mixed precision)")
    else:
        print(f"AMP        : Disabled (CPU mode)")
    print(f"Batch size : {batch_size}")
    print(f"Epochs     : {n_epochs}")
    print(f"{'='*60}")

    # ── Load pre-split data (no splitting here — done by extractor) ───────
    print(f"\nLoading {TRAIN_CSV} ...")
    train_df = pd.read_csv(TRAIN_CSV).dropna()
    print(f"  Train: {len(train_df)} rows | "
          f"Pos: {(train_df['label']==1).sum()} | "
          f"Neg: {(train_df['label']==0).sum()}")

    print(f"Loading {VAL_CSV} ...")
    val_df = pd.read_csv(VAL_CSV).dropna()
    print(f"  Val:   {len(val_df)} rows | "
          f"Pos: {(val_df['label']==1).sum()} | "
          f"Neg: {(val_df['label']==0).sum()}")

    # ── Tokenizer + model ─────────────────────────────────────────────────
    print(f"\nLoading tokenizer / model: {MODEL_NAME} ...")
    tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)
    model     = BertForSequenceClassification.from_pretrained(
        MODEL_NAME, num_labels=2
    )
    model.to(device)

    # ── Datasets + loaders (lazy tokenization — instant init) ─────────────
    train_ds = PlagiarismDataset(
        train_df["suspicious_text"], train_df["source_text"],
        train_df["label"], tokenizer, MAX_LENGTH
    )
    val_ds = PlagiarismDataset(
        val_df["suspicious_text"], val_df["source_text"],
        val_df["label"], tokenizer, MAX_LENGTH
    )
    print(f"  Datasets ready: {len(train_ds):,} train, {len(val_ds):,} val (lazy tokenization)")

    pin = device.type == "cuda"
    train_loader = DataLoader(
        train_ds, batch_size=batch_size, shuffle=True,
        num_workers=2, pin_memory=pin
    )
    val_loader = DataLoader(
        val_ds, batch_size=batch_size, shuffle=False,
        num_workers=2, pin_memory=pin
    )

    # ── Optimiser + scheduler ─────────────────────────────────────────────
    total_steps  = len(train_loader) * n_epochs
    warmup_steps = total_steps // 10
    optimiser    = AdamW(model.parameters(), lr=2e-5, weight_decay=0.01)
    scheduler    = get_linear_schedule_with_warmup(
        optimiser, warmup_steps, total_steps
    )

    # ── Training loop ─────────────────────────────────────────────────────
    best_f1 = 0.0
    for epoch in range(1, n_epochs + 1):
        print(f"\n══ Epoch {epoch}/{n_epochs} ══")
        model.train()
        running_loss = 0.0

        for batch in tqdm(train_loader, desc=f"  Training epoch {epoch}"):
            ids   = batch["input_ids"].to(device)
            mask  = batch["attention_mask"].to(device)
            types = batch.get("token_type_ids")
            if types is not None:
                types = types.to(device)
            lbls  = batch["labels"].to(device)

            kwargs = {"input_ids": ids, "attention_mask": mask, "labels": lbls}
            if types is not None:
                kwargs["token_type_ids"] = types

            optimiser.zero_grad()

            with autocast("cuda", enabled=use_amp):
                out  = model(**kwargs)
                loss = out.loss

            scaler.scale(loss).backward()
            scaler.unscale_(optimiser)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimiser)
            scaler.update()
            scheduler.step()
            running_loss += loss.item()

        avg_loss = running_loss / len(train_loader)
        print(f"  Train loss: {avg_loss:.4f}")

        # Validation
        val_metrics = evaluate_model(model, val_loader, device)
        print(f"  Val → P: {val_metrics['precision']:.4f}  "
              f"R: {val_metrics['recall']:.4f}  "
              f"F1: {val_metrics['f1']:.4f}  "
              f"Acc: {val_metrics['accuracy']:.4f}")

        if val_metrics["f1"] > best_f1:
            best_f1 = val_metrics["f1"]
            model.save_pretrained(OUTPUT_DIR)
            tokenizer.save_pretrained(OUTPUT_DIR)
            print(f"  ✅ Best model saved to {OUTPUT_DIR}/  (F1={best_f1:.4f})")

    print(f"\n{'='*60}")
    print(f"Training complete. Best validation F1: {best_f1:.4f}")
    print(f"Model saved at: {OUTPUT_DIR}/")
    print(f"Next step: python evaluate.py")
    print(f"{'='*60}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=3,
                        help="Training epochs (default 3)")
    parser.add_argument("--batch",  type=int, default=16,
                        help="Batch size (default 16, use 32 for T4 GPU)")
    args = parser.parse_args()
    main(args.epochs, args.batch)
